### ISSUE TITLE
Relayer: Restore partial transport execution mode

### ISSUE THREAD

**Issue by tilacog** [eigerco/solana-axelar#229]
After #191, the Relayer lost its capacity to be configured partially to run in only one transport direction.

The configuration parsing only succeeds if all environment variables for all transport directions are defined.

**Expected behavior**
Configuring the Relayer only for a single transport direction should be possible.

**Comment by roberts-ivanovs** [comment]
Summary:
On the team call on 29.04.2024 we came to the following consensus:
- move forward with the toml file based approach
- toml file will be mounted as a volume at `tbd` location for the relayer to read
- we provide the "parse $ENV as env variables" ability described [here](https://github.com/eigerco/solana-axelar/issues/229#issuecomment-2079740832)
- currently, we will provide the private key as a k8s secret (and it would get injected when parsing the toml file config), with the intention that later we can use HSMs (not any time soon tho)
